// <auto-generated />
namespace MvcProject.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_ımage_file : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_ımage_file));
        
        string IMigrationMetadata.Id
        {
            get { return "202106051909526_mig_ımage_file"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
