// <auto-generated />
namespace MvcProject.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migimaglength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migimaglength));
        
        string IMigrationMetadata.Id
        {
            get { return "202107081016351_mig-imaglength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
